[package]
name = "df11-codec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rayon = "1"
regex = "1"
toml = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10"

[dev-dependencies]
df11-fixtures = { path = "../df11-fixtures" }
